#docker config create conf ./fluentd/conf/fluent.conf
#docker network create --driver overlay elk
#Error response from daemon: dial tcp: lookup fluentdhost: Temporary failure in name resolution
version: "3.3"
services:
  web:
    image: httpd
    networks:
      - efk
    depends_on:
      - fluentdhost
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentdhost:24224
        tag: httpd.access
  nginx:
    image: sreeharshav/rollingupdate:v4
    networks:
      - efk
    depends_on:
      - fluentdhost
    ports:
      - "8000:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentdhost:24224
        tag: nginx.access

  fluentdhost:
    image: sreeharshav/efk_fluentd:v1
    networks:
      - efk
    depends_on:
      - elasticsearch
    configs:
       - source: conf
         target: /fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    networks:
      - efk
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    networks:
      - efk
    ports:
      - "5601:5601"
configs:
   conf:
     external: true
networks:
  efk:
    external: true
